apply plugin: "java"
apply plugin: 'maven-publish'

repositories{
    mavenCentral()
    maven{ url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven{ url 'https://www.jitpack.io' }
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

dependencies{
    implementation project(":plugin")
}

jar{
    dependsOn("client:jar")
    dependsOn("plugin:jar")

    archiveFileName = "${base.archivesName}.jar"
    from{
        configurations.runtimeClasspath.collect{it.isDirectory() ? it : zipTree(it)}
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'net.ddns.mindustry'
            artifactId = 'MindustryDatabase'
            version = '1.0'

            from components.java
        }
    }
}
