[versions]
jooq       = "3.19.18"
postgresql = "42.7.5"
argon2     = "2.11"
jna        = "5.16.0"
jackson    = "2.19.0"

[plugins]
jooqCodegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq"}

[libraries]
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
jooqPostgresqlExtension = {module = "org.jooq:jooq-postgres-extensions", version.ref = "jooq" }
argon2 = { module = "de.mkammerer:argon2-jvm", version.ref = "argon2" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson"}