buildscript {
    ext.kotlin_version = '2.3.0'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.3.21'
}

apply plugin: "java"
apply plugin: 'maven-publish'
apply plugin: 'kotlin'

group = 'com.github.mindustry-ddns-net'
version '1.0'

sourceSets.main.java.srcDirs = ["src"]

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories{
    mavenCentral()
    maven{ url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven{ url 'https://www.jitpack.io' }
}

ext{
    //the build number that this plugin is made for
    mindustryVersion = 'v157.4'
    jabelVersion = "93fde537c7"
    segment = "0.2.1"
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

dependencies{
    compileOnly "com.github.Anuken.Arc:arc-core:$mindustryVersion"
    compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"
    annotationProcessor "com.github.Anuken:jabel:$jabelVersion"
    implementation project(':client')

    implementation "com.github.mindustry-ddns-net:segment:$segment"

    implementation libs.jooq
    implementation libs.jooqExt
    implementation "org.jetbrains.kotlin:kotlin-reflect:2.3.0"

    implementation 'com.akuleshov7:ktoml-core:0.7.1'
    implementation 'com.akuleshov7:ktoml-file:0.7.1'
}

jar{
    dependsOn(":client:jar")

    archiveFileName = "${base.archivesName}.jar"
    from{
        configurations.runtimeClasspath.collect{it.isDirectory() ? it : zipTree(it)}
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}

//wrapper {
//    gradleVersion = "7.3.3"
//    distributionType = Wrapper.DistributionType.ALL
//}

kotlin {
    jvmToolchain(25)
}
